import type { InventoryItem } from "./types";

export const MOCK_ITEMS: InventoryItem[] = [
  // === CRITICAL DEATH PILE ===
  {
    id: "1",
    user_id: "demo",
    title: "Vintage Levi's 501 Jeans 34x32 Distressed Worn Fade 90s Grunge",
    platform: "eBay",
    price: 45.0,
    days_listed: 312,
    category: "Vintage Clothing",
    image_url: undefined,
    item_specifics_complete: false,
    image_count: 2,
    title_keyword_strength: 72,
    status: "active",
    created_at: new Date(Date.now() - 312 * 86400000).toISOString(),
  },
  {
    id: "2",
    user_id: "demo",
    title: "Air Jordan 1 Retro High OG Chicago 2015 Size 11",
    platform: "eBay",
    price: 285.0,
    days_listed: 245,
    category: "Sneakers",
    image_url: undefined,
    item_specifics_complete: false,
    image_count: 3,
    title_keyword_strength: 80,
    status: "active",
    created_at: new Date(Date.now() - 245 * 86400000).toISOString(),
  },
  {
    id: "3",
    user_id: "demo",
    title: "Nintendo 64 Console Bundle N64 With 2 Controllers",
    platform: "eBay",
    price: 120.0,
    days_listed: 198,
    category: "Electronics",
    image_url: undefined,
    item_specifics_complete: false,
    image_count: 1,
    title_keyword_strength: 55,
    status: "active",
    created_at: new Date(Date.now() - 198 * 86400000).toISOString(),
  },
  {
    id: "4",
    user_id: "demo",
    title: "Ralph Lauren Polo Bear Knit Sweater Large Rare 1990s",
    platform: "eBay",
    price: 95.0,
    days_listed: 421,
    category: "Vintage Clothing",
    image_url: undefined,
    item_specifics_complete: false,
    image_count: 1,
    title_keyword_strength: 68,
    status: "active",
    created_at: new Date(Date.now() - 421 * 86400000).toISOString(),
  },
  {
    id: "5",
    user_id: "demo",
    title: "Funko Pop Lot 12 Mixed Marvel DC Hot Topic Exclusives",
    platform: "eBay",
    price: 8.0,
    days_listed: 380,
    category: "Collectibles",
    image_url: undefined,
    item_specifics_complete: false,
    image_count: 1,
    title_keyword_strength: 40,
    status: "active",
    created_at: new Date(Date.now() - 380 * 86400000).toISOString(),
  },

  // === HIGH RISK ===
  {
    id: "6",
    user_id: "demo",
    title: "Supreme Box Logo Hoodie FW18 Black Large Authentic",
    platform: "eBay",
    price: 340.0,
    days_listed: 142,
    category: "Streetwear",
    image_url: undefined,
    item_specifics_complete: true,
    image_count: 5,
    title_keyword_strength: 88,
    status: "active",
    created_at: new Date(Date.now() - 142 * 86400000).toISOString(),
  },
  {
    id: "7",
    user_id: "demo",
    title: "Sony PlayStation 2 PS2 Slim Silver Console SCPH-77001",
    platform: "eBay",
    price: 89.0,
    days_listed: 156,
    category: "Electronics",
    image_url: undefined,
    item_specifics_complete: false,
    image_count: 2,
    title_keyword_strength: 65,
    status: "active",
    created_at: new Date(Date.now() - 156 * 86400000).toISOString(),
  },
  {
    id: "8",
    user_id: "demo",
    title: "Coach Leather Purse Brown Shoulder Bag Vintage Y2K",
    platform: "Poshmark",
    price: 55.0,
    days_listed: 167,
    category: "Handbags",
    image_url: undefined,
    item_specifics_complete: false,
    image_count: 3,
    title_keyword_strength: 58,
    status: "active",
    created_at: new Date(Date.now() - 167 * 86400000).toISOString(),
  },
  {
    id: "9",
    user_id: "demo",
    title: "Pyrex Vision Hoodie Red 2012 Virgil Abloh Size M",
    platform: "eBay",
    price: 450.0,
    days_listed: 98,
    category: "Streetwear",
    image_url: undefined,
    item_specifics_complete: false,
    image_count: 4,
    title_keyword_strength: 82,
    status: "active",
    created_at: new Date(Date.now() - 98 * 86400000).toISOString(),
  },
  {
    id: "10",
    user_id: "demo",
    title: "Carhartt WIP Detroit Jacket Brown Canvas Lined Medium",
    platform: "Depop",
    price: 78.0,
    days_listed: 112,
    category: "Workwear",
    image_url: undefined,
    item_specifics_complete: false,
    image_count: 2,
    title_keyword_strength: 70,
    status: "active",
    created_at: new Date(Date.now() - 112 * 86400000).toISOString(),
  },

  // === MEDIUM RISK ===
  {
    id: "11",
    user_id: "demo",
    title: "Nike SB Dunk Low Pro Hemp 2021 Size 10.5 DS",
    platform: "eBay",
    price: 165.0,
    days_listed: 67,
    category: "Sneakers",
    image_url: undefined,
    item_specifics_complete: true,
    image_count: 6,
    title_keyword_strength: 85,
    status: "active",
    created_at: new Date(Date.now() - 67 * 86400000).toISOString(),
  },
  {
    id: "12",
    user_id: "demo",
    title: "Polaroid SX-70 Land Camera Vintage Working Tested",
    platform: "eBay",
    price: 75.0,
    days_listed: 74,
    category: "Cameras",
    image_url: undefined,
    item_specifics_complete: true,
    image_count: 4,
    title_keyword_strength: 78,
    status: "active",
    created_at: new Date(Date.now() - 74 * 86400000).toISOString(),
  },
  {
    id: "13",
    user_id: "demo",
    title: "Tommy Hilfiger Flag Crewneck Sweatshirt XL 90s Vintage",
    platform: "Mercari",
    price: 32.0,
    days_listed: 58,
    category: "Vintage Clothing",
    image_url: undefined,
    item_specifics_complete: false,
    image_count: 2,
    title_keyword_strength: 62,
    status: "active",
    created_at: new Date(Date.now() - 58 * 86400000).toISOString(),
  },
  {
    id: "14",
    user_id: "demo",
    title: "Bearbrick 400% Medicom Toy KAWS Companion 2020",
    platform: "eBay",
    price: 210.0,
    days_listed: 83,
    category: "Collectibles",
    image_url: undefined,
    item_specifics_complete: true,
    image_count: 3,
    title_keyword_strength: 90,
    status: "active",
    created_at: new Date(Date.now() - 83 * 86400000).toISOString(),
  },
  {
    id: "15",
    user_id: "demo",
    title: "Adidas Yeezy Boost 350 V2 Zebra CP9654 Size 9",
    platform: "StockX",
    price: 225.0,
    days_listed: 45,
    category: "Sneakers",
    image_url: undefined,
    item_specifics_complete: true,
    image_count: 7,
    title_keyword_strength: 92,
    status: "active",
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
  },

  // === LOW RISK / HEALTHY ===
  {
    id: "16",
    user_id: "demo",
    title: "Carhartt Beanie Watch Hat Black OG Acrylic Knit",
    platform: "eBay",
    price: 18.0,
    days_listed: 12,
    category: "Accessories",
    image_url: undefined,
    item_specifics_complete: true,
    image_count: 5,
    title_keyword_strength: 80,
    status: "active",
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
  },
  {
    id: "17",
    user_id: "demo",
    title: "Stussy 8 Ball Fleece Crew Sweatshirt Black Large 2023",
    platform: "Depop",
    price: 85.0,
    days_listed: 8,
    category: "Streetwear",
    image_url: undefined,
    item_specifics_complete: true,
    image_count: 8,
    title_keyword_strength: 88,
    status: "active",
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
  },
  {
    id: "18",
    user_id: "demo",
    title: "Vintage Marlboro Racing Jacket Medium USA Made 1995",
    platform: "eBay",
    price: 125.0,
    days_listed: 22,
    category: "Vintage Clothing",
    image_url: undefined,
    item_specifics_complete: true,
    image_count: 9,
    title_keyword_strength: 91,
    status: "active",
    created_at: new Date(Date.now() - 22 * 86400000).toISOString(),
  },
  {
    id: "19",
    user_id: "demo",
    title: "New Balance 990v3 Made in USA Grey M990GL3 Size 11.5",
    platform: "eBay",
    price: 195.0,
    days_listed: 5,
    category: "Sneakers",
    image_url: undefined,
    item_specifics_complete: true,
    image_count: 10,
    title_keyword_strength: 95,
    status: "active",
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: "20",
    user_id: "demo",
    title: "Pokemon Base Set Charizard Holo 4/102 PSA 7",
    platform: "eBay",
    price: 380.0,
    days_listed: 18,
    category: "Collectibles",
    image_url: undefined,
    item_specifics_complete: true,
    image_count: 6,
    title_keyword_strength: 96,
    status: "active",
    created_at: new Date(Date.now() - 18 * 86400000).toISOString(),
  },
  // === SOLD ITEMS (for historical context) ===
  {
    id: "21",
    user_id: "demo",
    title: "Vintage Starter Jacket Chicago Bulls Snap Satin XL",
    platform: "eBay",
    price: 145.0,
    days_listed: 14,
    category: "Vintage Clothing",
    image_url: undefined,
    item_specifics_complete: true,
    image_count: 7,
    title_keyword_strength: 87,
    status: "sold",
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
];

export const DEMO_USER = {
  id: "demo",
  email: "seller@rejectedeconomy.com",
};
